### ISSUE TITLE
deviceToken in react native

### ISSUE THREAD

**Issue by PanRada** [CatalystCode/react-native-azurenotificationhub#31]
Any can give some smart solution for read device Token's  ?

In iOS implementation for react native we need use  
var remoteNotificationsDeviceToken = ''
where is that token  ? 

Pls any direction, help, solution

**Comment by phongcao** [comment]
Hi @PanRada, please see #30.

**Comment by arthwood** [comment]
Hi @phongcao , first of all thank you for this library - it makes the integration with azure a lot easier!
Just was wondering if it is possible to get the counterpart FCM/GCM token available on Android.
Since I register/install the app in hub from the backend for iOS, it would make it more consistent to do the same approach for Android. However, instead I have to register in the hub for Android on device, then pass hub registration id to my backend so it can find FCM/GCM token through the hub API.
I was looking in the sources, but it doesn't seem to make it available in react-native code.

Instead of that, I could move the registration for iOS from backend to device, but then it is not possible to do the installation as far as I'm aware.

**Comment by phongcao** [comment]
@arthwood I understand where you're coming from. Unfortunately, this is not currently supported. At minimum, would it help if we add a new event to notify the app whenever it receives a new device token (the notification hub stills invokes the registration method in this case)?

https://github.com/CatalystCode/react-native-azurenotificationhub/blob/c6fe70272dd7d7449a81a2cf965f72304c3644a3/android/src/main/java/com/azure/reactnative/notificationhub/ReactNativeRegistrationIntentService.java#L67

**Comment by arthwood** [comment]
Yes, I think that would be useful. 
I eventually moved the registration for iOS from BE to FE and dropped the installation process (it seems overcomplicated and I found it's behaviour not quite consistent).
